In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
pd.set_option('display.max_columns', None)

In [2]:
raw_data = pd.read_csv('dataset.csv')

In [3]:
raw_data

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [4]:
raw_data.describe(include='all')

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
count,7043,7043,7043.000000,7043,7043,7043.000000,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043.000000,7043,7043
unique,7043,2,NaN,2,2,NaN,2,3,3,3,3,3,3,3,3,3,2,4,NaN,6531,2
top,6916-HIJSE,Male,NaN,No,No,NaN,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,NaN,20.2,No
freq,1,3555,NaN,3641,4933,NaN,6361,3390,3096,3498,3088,3095,3473,2810,2785,3875,4171,2365,NaN,11,5174
mean,NaN,NaN,0.162147,NaN,NaN,32.371149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.761692,NaN,NaN
std,NaN,NaN,0.368612,NaN,NaN,24.559481,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.090047,NaN,NaN
min,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.250000,NaN,NaN
25%,NaN,NaN,0.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.500000,NaN,NaN
50%,NaN,NaN,0.000000,NaN,NaN,29.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.350000,NaN,NaN
75%,NaN,NaN,0.000000,NaN,NaN,55.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.850000,NaN,NaN
max,NaN,NaN,1.000000,NaN,NaN,72.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.750000,NaN,NaN

In [5]:
print ("Rows     : " ,raw_data.shape[0])
print ("Columns  : " ,raw_data.shape[1])
print ("\nFeatures : \n" ,raw_data.columns.tolist())
print ("\nMissing values :  ", raw_data.isnull().sum().values.sum())
print ("\nUnique values :  \n",raw_data.nunique())

raw_data.dtypes

Rows     :  7043
Columns  :  21

Features :
 ['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

Missing values :   0

Unique values :
 customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [6]:
pd.set_option('display.max_row', 1000)

In [7]:
raw_data.TotalCharges = raw_data.TotalCharges.replace(' ',np.nan)

In [8]:
raw_data.TotalCharges.dtype

dtype('O')

In [9]:
raw_data.TotalCharges = raw_data.TotalCharges.astype('float')

# Checking Unique Value

In [10]:
checking_unique_column= [
    'gender', 'Partner','Dependents','PhoneService','MultipleLines','InternetService','OnlineSecurity','DeviceProtection','TechSupport','StreamingTV','StreamingMovies',
    'Contract','PaperlessBilling','PaymentMethod','Churn'
];

In [11]:
for row in checking_unique_column:
    print (row+':')
    print(raw_data[row].unique())

gender:
['Female' 'Male']
Partner:
['Yes' 'No']
Dependents:
['No' 'Yes']
PhoneService:
['No' 'Yes']
MultipleLines:
['No phone service' 'No' 'Yes']
InternetService:
['DSL' 'Fiber optic' 'No']
OnlineSecurity:
['No' 'Yes' 'No internet service']
DeviceProtection:
['No' 'Yes' 'No internet service']
TechSupport:
['No' 'Yes' 'No internet service']
StreamingTV:
['No' 'Yes' 'No internet service']
StreamingMovies:
['No' 'Yes' 'No internet service']
Contract:
['Month-to-month' 'One year' 'Two year']
PaperlessBilling:
['Yes' 'No']
PaymentMethod:
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
Churn:
['No' 'Yes']

# Dummy Data

In [12]:
def get_dummies(data):
    data_dummies = pd.get_dummies(data,drop_first=True)
    return data_dummies

In [13]:
data = raw_data.copy()

In [14]:
data

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [15]:
gender_dummies = get_dummies(data.gender)

In [16]:
gender_dummies

      Male
0        0
1        1
2        1
3        1
4        0
...    ...
7038     1
7039     0
7040     0
7041     1
7042     1

[7043 rows x 1 columns]

In [17]:
data_with_gender_dummies = pd.concat([data,gender_dummies],axis=1)

In [18]:
data_with_gender_dummies

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Male
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No,1
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,1
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No,1
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No,0
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,0
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes,1
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,1

In [19]:
data_drop_gender = data_with_gender_dummies.drop(labels=['gender'],axis=1)

In [20]:
data_drop_gender

,customerID,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Male
0,7590-VHVEG,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0
1,5575-GNVDE,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No,1
2,3668-QPYBK,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1
3,7795-CFOCW,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,1
4,9237-HQITU,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No,1
7039,2234-XADUH,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No,0
7040,4801-JZAZL,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,0
7041,8361-LTMKD,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes,1
7042,3186-AJIEK,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,1

In [21]:
senior_citizen = get_dummies(data_drop_gender.SeniorCitizen)

In [22]:
senior_citizen.columns = ['isCitizen']

In [23]:
senior_citizen

      isCitizen
0             0
1             0
2             0
3             0
4             0
...         ...
7038          0
7039          0
7040          0
7041          1
7042          0

[7043 rows x 1 columns]

In [24]:
data_with_senior_dummies = pd.concat([data_drop_gender,senior_citizen],axis=1)

In [25]:
data_drop_senior_citizen = data_with_senior_dummies.drop(labels=['SeniorCitizen'],axis=1)

In [26]:
data_drop_senior_citizen

,customerID,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Male,isCitizen
0,7590-VHVEG,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0,0
1,5575-GNVDE,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No,1,0
2,3668-QPYBK,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,0
3,7795-CFOCW,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,1,0
4,9237-HQITU,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No,1,0
7039,2234-XADUH,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No,0,0
7040,4801-JZAZL,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,0
7041,8361-LTMKD,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes,1,1
7042,3186-AJIEK,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,1,0

In [27]:
partner_dummy = get_dummies(data_drop_senior_citizen.Partner)
partner_dummy.columns = ['HavePartner']

In [28]:
partner_dummy

      HavePartner
0               1
1               0
2               0
3               0
4               0
...           ...
7038            1
7039            1
7040            1
7041            1
7042            0

[7043 rows x 1 columns]

In [29]:
data_with_senior_dummies = pd.concat([data_drop_senior_citizen,partner_dummy],axis=1)
data_drop_partner = data_with_senior_dummies.drop(labels=['Partner'],axis=1)
data_drop_partner

,customerID,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Male,isCitizen,HavePartner
0,7590-VHVEG,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0,0,1
1,5575-GNVDE,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No,1,0,0
2,3668-QPYBK,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,0,0
3,7795-CFOCW,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,1,0,0
4,9237-HQITU,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No,1,0,1
7039,2234-XADUH,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No,0,0,1
7040,4801-JZAZL,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,0,1
7041,8361-LTMKD,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes,1,1,1
7042,3186-AJIEK,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,1,0,0

In [30]:
dependents_dummy = get_dummies(data_drop_partner.Dependents)
dependents_dummy.columns = ['HaveDepedents']

In [31]:
data_with_dependents_dummies = pd.concat([data_drop_partner,dependents_dummy],axis=1)
data_drop_dependents = data_with_dependents_dummies.drop(labels=['Dependents'],axis=1)
data_drop_dependents

,customerID,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Male,isCitizen,HavePartner,HaveDepedents
0,7590-VHVEG,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0,0,1,0
1,5575-GNVDE,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No,1,0,0,0
2,3668-QPYBK,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,0,0,0
3,7795-CFOCW,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,1,0,0,0
4,9237-HQITU,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No,1,0,1,1
7039,2234-XADUH,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No,0,0,1,1
7040,4801-JZAZL,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,0,1,1
7041,8361-LTMKD,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes,1,1,1,0
7042,3186-AJIEK,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,1,0,0,0

In [32]:
phone_services_dummy = get_dummies(data_drop_partner.PhoneService)
phone_services_dummy.columns = ['PhoneServices']

In [33]:
data_with_phone_services_dummies = pd.concat([data_drop_dependents,phone_services_dummy],axis=1)
data_drop_phones = data_with_phone_services_dummies.drop(labels=['PhoneService'],axis=1)
data_drop_phones

,customerID,tenure,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Male,isCitizen,HavePartner,HaveDepedents,PhoneServices
0,7590-VHVEG,1,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0,0,1,0,0
1,5575-GNVDE,34,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No,1,0,0,0,1
2,3668-QPYBK,2,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,0,0,0,1
3,7795-CFOCW,45,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,1,0,0,0,0
4,9237-HQITU,2,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,24,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No,1,0,1,1,1
7039,2234-XADUH,72,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No,0,0,1,1,1
7040,4801-JZAZL,11,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,0,1,1,0
7041,8361-LTMKD,4,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes,1,1,1,0,1
7042,3186-AJIEK,66,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,1,0,0,0,1

In [34]:
MultipleLines = get_dummies(data_drop_partner.MultipleLines)
MultipleLines

      No phone service  Yes
0                    1    0
1                    0    0
2                    0    0
3                    1    0
4                    0    0
...                ...  ...
7038                 0    1
7039                 0    1
7040                 1    0
7041                 0    1
7042                 0    0

[7043 rows x 2 columns]

In [35]:
MultipleLines.columns = ['MultiplineLines_No_phone_service','Multiplines_YES']

In [36]:
data_with_multiplelines_dummies = pd.concat([data_drop_phones,MultipleLines],axis=1)
data_drop_multiplelines = data_with_multiplelines_dummies.drop(labels=['MultipleLines'],axis=1)
data_drop_multiplelines

,customerID,tenure,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Male,isCitizen,HavePartner,HaveDepedents,PhoneServices,MultiplineLines_No_phone_service,Multiplines_YES
0,7590-VHVEG,1,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0,0,1,0,0,1,0
1,5575-GNVDE,34,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No,1,0,0,0,1,0,0
2,3668-QPYBK,2,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,0,0,0,1,0,0
3,7795-CFOCW,45,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,1,0,0,0,0,1,0
4,9237-HQITU,2,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,24,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No,1,0,1,1,1,0,1
7039,2234-XADUH,72,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No,0,0,1,1,1,0,1
7040,4801-JZAZL,11,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,0,1,1,0,1,0
7041,8361-LTMKD,4,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes,1,1,1,0,1,0,1
7042,3186-AJIEK,66,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,1,0,0,0,1,0,0

In [37]:
InternetService = get_dummies(data_drop_partner.InternetService)
InternetService

      Fiber optic  No
0               0   0
1               0   0
2               0   0
3               0   0
4               1   0
...           ...  ..
7038            0   0
7039            1   0
7040            0   0
7041            1   0
7042            1   0

[7043 rows x 2 columns]

In [38]:
InternetService.columns = ['InternetService_Fiber_Optic','InternetService_No']
data_with_internet_services_dummy = pd.concat([data_drop_multiplelines,InternetService],axis=1)
data_drop_internet_services = data_with_internet_services_dummy.drop(labels=['InternetService'],axis=1)
data_drop_internet_services

,customerID,tenure,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Male,isCitizen,HavePartner,HaveDepedents,PhoneServices,MultiplineLines_No_phone_service,Multiplines_YES,InternetService_Fiber_Optic,InternetService_No
0,7590-VHVEG,1,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0,0,1,0,0,1,0,0,0
1,5575-GNVDE,34,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No,1,0,0,0,1,0,0,0,0
2,3668-QPYBK,2,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,0,0,0,1,0,0,0,0
3,7795-CFOCW,45,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,1,0,0,0,0,1,0,0,0
4,9237-HQITU,2,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,24,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No,1,0,1,1,1,0,1,0,0
7039,2234-XADUH,72,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No,0,0,1,1,1,0,1,1,0
7040,4801-JZAZL,11,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,0,1,1,0,1,0,0,0
7041,8361-LTMKD,4,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes,1,1,1,0,1,0,1,1,0
7042,3186-AJIEK,66,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,1,0,0,0,1,0,0,1,0

In [39]:
OnlineSecurity = get_dummies(data_drop_partner.OnlineSecurity)
OnlineSecurity

      No internet service  Yes
0                       0    0
1                       0    1
2                       0    1
3                       0    1
4                       0    0
...                   ...  ...
7038                    0    1
7039                    0    0
7040                    0    1
7041                    0    0
7042                    0    1

[7043 rows x 2 columns]

In [40]:
OnlineSecurity.columns = ['OnlineSecurity_No_Internet_Service','OnlineSecurity_Yes']
data_with_onlines_security_dummy = pd.concat([data_drop_internet_services,OnlineSecurity],axis=1)
data_drop_onlines_security = data_with_onlines_security_dummy.drop(labels=['OnlineSecurity'],axis=1)
data_drop_onlines_security

,customerID,tenure,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Male,isCitizen,HavePartner,HaveDepedents,PhoneServices,MultiplineLines_No_phone_service,Multiplines_YES,InternetService_Fiber_Optic,InternetService_No,OnlineSecurity_No_Internet_Service,OnlineSecurity_Yes
0,7590-VHVEG,1,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0,0,1,0,0,1,0,0,0,0,0
1,5575-GNVDE,34,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No,1,0,0,0,1,0,0,0,0,0,1
2,3668-QPYBK,2,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,0,0,0,1,0,0,0,0,0,1
3,7795-CFOCW,45,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,1,0,0,0,0,1,0,0,0,0,1
4,9237-HQITU,2,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,0,0,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,24,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No,1,0,1,1,1,0,1,0,0,0,1
7039,2234-XADUH,72,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No,0,0,1,1,1,0,1,1,0,0,0
7040,4801-JZAZL,11,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,0,1,1,0,1,0,0,0,0,1
7041,8361-LTMKD,4,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes,1,1,1,0,1,0,1,1,0,0,0
7042,3186-AJIEK,66,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,1,0,0,0,1,0,0,1,0,0,1

In [41]:
OnlineBackup = get_dummies(data_drop_partner.OnlineBackup)
OnlineBackup

      No internet service  Yes
0                       0    1
1                       0    0
2                       0    1
3                       0    0
4                       0    0
...                   ...  ...
7038                    0    0
7039                    0    1
7040                    0    0
7041                    0    0
7042                    0    0

[7043 rows x 2 columns]

In [42]:
OnlineBackup.columns = ['OnlineBackup_No_Internet_Service','OnlineBackup_Yes']
data_with_onlines_backup_dummy = pd.concat([data_drop_onlines_security,OnlineSecurity],axis=1)
data_drop_onlines_backup = data_with_onlines_backup_dummy.drop(labels=['OnlineBackup'],axis=1)
data_drop_onlines_backup

,customerID,tenure,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Male,isCitizen,HavePartner,HaveDepedents,PhoneServices,MultiplineLines_No_phone_service,Multiplines_YES,InternetService_Fiber_Optic,InternetService_No,OnlineSecurity_No_Internet_Service,OnlineSecurity_Yes,OnlineSecurity_No_Internet_Service,OnlineSecurity_Yes
0,7590-VHVEG,1,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0,0,1,0,0,1,0,0,0,0,0,0,0
1,5575-GNVDE,34,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No,1,0,0,0,1,0,0,0,0,0,1,0,1
2,3668-QPYBK,2,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,0,0,0,1,0,0,0,0,0,1,0,1
3,7795-CFOCW,45,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,1,0,0,0,0,1,0,0,0,0,1,0,1
4,9237-HQITU,2,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,0,0,0,1,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,24,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No,1,0,1,1,1,0,1,0,0,0,1,0,1
7039,2234-XADUH,72,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No,0,0,1,1,1,0,1,1,0,0,0,0,0
7040,4801-JZAZL,11,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,0,1,1,0,1,0,0,0,0,1,0,1
7041,8361-LTMKD,4,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes,1,1,1,0,1,0,1,1,0,0,0,0,0
7042,3186-AJIEK,66,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,1,0,0,0,1,0,0,1,0,0,1,0,1

In [43]:
DeviceProtection = get_dummies(data_drop_partner.DeviceProtection)
TechSupport = get_dummies(data_drop_partner.TechSupport)
StreamingTV = get_dummies(data_drop_partner.StreamingTV)
StreamingMovies = get_dummies(data_drop_partner.StreamingMovies)
Contract = get_dummies(data_drop_partner.Contract)
PaperlessBilling = get_dummies(data_drop_partner.PaperlessBilling)
PaymentMethod = get_dummies(data_drop_partner.PaymentMethod)

In [44]:
DeviceProtection

      No internet service  Yes
0                       0    0
1                       0    1
2                       0    0
3                       0    1
4                       0    0
...                   ...  ...
7038                    0    1
7039                    0    1
7040                    0    0
7041                    0    0
7042                    0    1

[7043 rows x 2 columns]

In [45]:
DeviceProtection.columns = ['DeviceProtection_No_Internet_Service','DeviceProtection_Yes']

In [46]:
TechSupport

      No internet service  Yes
0                       0    0
1                       0    0
2                       0    0
3                       0    1
4                       0    0
...                   ...  ...
7038                    0    1
7039                    0    0
7040                    0    0
7041                    0    0
7042                    0    1

[7043 rows x 2 columns]

In [47]:
TechSupport.columns = ['TechSupport_No_Internet_Service','TechSupport_Yes']

In [48]:
StreamingTV

      No internet service  Yes
0                       0    0
1                       0    0
2                       0    0
3                       0    0
4                       0    0
...                   ...  ...
7038                    0    1
7039                    0    1
7040                    0    0
7041                    0    0
7042                    0    1

[7043 rows x 2 columns]

In [49]:
StreamingTV.columns = ['StreamingTV_No_Internet_Service','StreamingTV_Yes']

In [50]:
StreamingMovies

      No internet service  Yes
0                       0    0
1                       0    0
2                       0    0
3                       0    0
4                       0    0
...                   ...  ...
7038                    0    1
7039                    0    1
7040                    0    0
7041                    0    0
7042                    0    1

[7043 rows x 2 columns]

In [51]:
StreamingMovies.columns = ['StreamingMovies_No_Internet_Service','StreamingMovies_Yes']

In [52]:
Contract

      One year  Two year
0            0         0
1            1         0
2            0         0
3            1         0
4            0         0
...        ...       ...
7038         1         0
7039         1         0
7040         0         0
7041         0         0
7042         0         1

[7043 rows x 2 columns]

In [53]:
Contract.columns = ['Contract_One_Year','Contract_Two_Year']

In [54]:
PaperlessBilling

      Yes
0       1
1       0
2       1
3       0
4       1
...   ...
7038    1
7039    1
7040    1
7041    1
7042    1

[7043 rows x 1 columns]

In [55]:
PaperlessBilling.columns = ['PaperlessBilling']

In [56]:
PaymentMethod

      Credit card (automatic)  Electronic check  Mailed check
0                           0                 1             0
1                           0                 0             1
2                           0                 0             1
3                           0                 0             0
4                           0                 1             0
...                       ...               ...           ...
7038                        0                 0             1
7039                        1                 0             0
7040                        0                 1             0
7041                        0                 0             1
7042                        0                 0             0

[7043 rows x 3 columns]

In [57]:
PaymentMethod.columns = ['PaymentMethod_Credit_card','PaymentMethod_Electronic_Check','PaymentMethod_Mailed_Check']

In [58]:
data_with_dummy = pd.concat([data_drop_onlines_backup,DeviceProtection,TechSupport,StreamingTV,Contract,PaperlessBilling,
                             PaymentMethod],axis=1)

In [59]:
data_with_dummy

,customerID,tenure,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Male,isCitizen,HavePartner,HaveDepedents,PhoneServices,MultiplineLines_No_phone_service,Multiplines_YES,InternetService_Fiber_Optic,InternetService_No,OnlineSecurity_No_Internet_Service,OnlineSecurity_Yes,OnlineSecurity_No_Internet_Service,OnlineSecurity_Yes,DeviceProtection_No_Internet_Service,DeviceProtection_Yes,TechSupport_No_Internet_Service,TechSupport_Yes,StreamingTV_No_Internet_Service,StreamingTV_Yes,Contract_One_Year,Contract_Two_Year,PaperlessBilling,PaymentMethod_Credit_card,PaymentMethod_Electronic_Check,PaymentMethod_Mailed_Check
0,7590-VHVEG,1,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0
1,5575-GNVDE,34,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No,1,0,0,0,1,0,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,1
2,3668-QPYBK,2,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,1
3,7795-CFOCW,45,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,1,0,0,0,0,1,0,0,0,0,1,0,1,0,1,0,1,0,0,1,0,0,0,0,0
4,9237-HQITU,2,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,24,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No,1,0,1,1,1,0,1,0,0,0,1,0,1,0,1,0,1,0,1,1,0,1,0,0,1
7039,2234-XADUH,72,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No,0,0,1,1,1,0,1,1,0,0,0,0,0,0,1,0,0,0,1,1,0,1,1,0,0
7040,4801-JZAZL,11,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,0,1,1,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,1,0
7041,8361-LTMKD,4,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes,1,1,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1
7042,3186-AJIEK,66,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,1,0,0,0,1,0,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,1,0,0,0

In [60]:
data_done_with_dummy_data = data_with_dummy.drop(labels=['DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 
                                                          'Contract', 'PaperlessBilling', 'PaymentMethod'],axis=1)

In [61]:
data_done_with_dummy_data

,customerID,tenure,MonthlyCharges,TotalCharges,Churn,Male,isCitizen,HavePartner,HaveDepedents,PhoneServices,MultiplineLines_No_phone_service,Multiplines_YES,InternetService_Fiber_Optic,InternetService_No,OnlineSecurity_No_Internet_Service,OnlineSecurity_Yes,OnlineSecurity_No_Internet_Service,OnlineSecurity_Yes,DeviceProtection_No_Internet_Service,DeviceProtection_Yes,TechSupport_No_Internet_Service,TechSupport_Yes,StreamingTV_No_Internet_Service,StreamingTV_Yes,Contract_One_Year,Contract_Two_Year,PaymentMethod_Credit_card,PaymentMethod_Electronic_Check,PaymentMethod_Mailed_Check
0,7590-VHVEG,1,29.85,29.85,No,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1,5575-GNVDE,34,56.95,1889.50,No,1,0,0,0,1,0,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,0,0,1
2,3668-QPYBK,2,53.85,108.15,Yes,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1
3,7795-CFOCW,45,42.30,1840.75,No,1,0,0,0,0,1,0,0,0,0,1,0,1,0,1,0,1,0,0,1,0,0,0,0
4,9237-HQITU,2,70.70,151.65,Yes,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,24,84.80,1990.50,No,1,0,1,1,1,0,1,0,0,0,1,0,1,0,1,0,1,0,1,1,0,0,0,1
7039,2234-XADUH,72,103.20,7362.90,No,0,0,1,1,1,0,1,1,0,0,0,0,0,0,1,0,0,0,1,1,0,1,0,0
7040,4801-JZAZL,11,29.60,346.45,No,0,0,1,1,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0
7041,8361-LTMKD,4,74.40,306.60,Yes,1,1,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
7042,3186-AJIEK,66,105.65,6844.50,No,1,0,0,0,1,0,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0

In [64]:
data_done_with_dummy_data['Churn'] =data_done_with_dummy_data['Churn'].map({'Yes':1 ,'No':0})

C:\Users\COMPUTER\Anaconda3\envs\tf-gpu\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [65]:
data_done_with_dummy_data

,customerID,tenure,MonthlyCharges,TotalCharges,Churn,Male,isCitizen,HavePartner,HaveDepedents,PhoneServices,MultiplineLines_No_phone_service,Multiplines_YES,InternetService_Fiber_Optic,InternetService_No,OnlineSecurity_No_Internet_Service,OnlineSecurity_Yes,OnlineSecurity_No_Internet_Service,OnlineSecurity_Yes,DeviceProtection_No_Internet_Service,DeviceProtection_Yes,TechSupport_No_Internet_Service,TechSupport_Yes,StreamingTV_No_Internet_Service,StreamingTV_Yes,Contract_One_Year,Contract_Two_Year,PaymentMethod_Credit_card,PaymentMethod_Electronic_Check,PaymentMethod_Mailed_Check
0,7590-VHVEG,1,29.85,29.85,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1,5575-GNVDE,34,56.95,1889.50,0,1,0,0,0,1,0,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,0,0,1
2,3668-QPYBK,2,53.85,108.15,1,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1
3,7795-CFOCW,45,42.30,1840.75,0,1,0,0,0,0,1,0,0,0,0,1,0,1,0,1,0,1,0,0,1,0,0,0,0
4,9237-HQITU,2,70.70,151.65,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,24,84.80,1990.50,0,1,0,1,1,1,0,1,0,0,0,1,0,1,0,1,0,1,0,1,1,0,0,0,1
7039,2234-XADUH,72,103.20,7362.90,0,0,0,1,1,1,0,1,1,0,0,0,0,0,0,1,0,0,0,1,1,0,1,0,0
7040,4801-JZAZL,11,29.60,346.45,0,0,0,1,1,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0
7041,8361-LTMKD,4,74.40,306.60,1,1,1,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
7042,3186-AJIEK,66,105.65,6844.50,0,1,0,0,0,1,0,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0

In [67]:
data_done_with_dummy_data.to_csv('preprocessing_data.csv')

In [70]:
data_done_with_dummy_data.columns

Index(['customerID', 'tenure', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'Male', 'isCitizen', 'HavePartner', 'HaveDepedents', 'PhoneServices',
       'MultiplineLines_No_phone_service', 'Multiplines_YES',
       'InternetService_Fiber_Optic', 'InternetService_No',
       'OnlineSecurity_No_Internet_Service', 'OnlineSecurity_Yes',
       'OnlineSecurity_No_Internet_Service', 'OnlineSecurity_Yes',
       'DeviceProtection_No_Internet_Service', 'DeviceProtection_Yes',
       'TechSupport_No_Internet_Service', 'TechSupport_Yes',
       'StreamingTV_No_Internet_Service', 'StreamingTV_Yes',
       'Contract_One_Year', 'Contract_Two_Year', 'PaymentMethod_Credit_card',
       'PaymentMethod_Electronic_Check', 'PaymentMethod_Mailed_Check'],
      dtype='object')

In [74]:
data_done_with_dummy_data = data_done_with_dummy_data[['customerID',
       'Male', 'isCitizen', 'HavePartner', 'HaveDepedents', 'PhoneServices',
       'MultiplineLines_No_phone_service', 'Multiplines_YES',
       'InternetService_Fiber_Optic', 'InternetService_No',
       'OnlineSecurity_No_Internet_Service', 'OnlineSecurity_Yes',
       'OnlineSecurity_No_Internet_Service', 'OnlineSecurity_Yes',
       'DeviceProtection_No_Internet_Service', 'DeviceProtection_Yes',
       'TechSupport_No_Internet_Service', 'TechSupport_Yes',
       'StreamingTV_No_Internet_Service', 'StreamingTV_Yes',
       'Contract_One_Year', 'Contract_Two_Year', 'PaymentMethod_Credit_card',
       'PaymentMethod_Electronic_Check', 'PaymentMethod_Mailed_Check','tenure', 'MonthlyCharges', 'TotalCharges', 'Churn']]

In [75]:
data_done_with_dummy_data

,customerID,Male,isCitizen,HavePartner,HaveDepedents,PhoneServices,MultiplineLines_No_phone_service,Multiplines_YES,InternetService_Fiber_Optic,InternetService_No,OnlineSecurity_No_Internet_Service,OnlineSecurity_No_Internet_Service,OnlineSecurity_Yes,OnlineSecurity_Yes,OnlineSecurity_No_Internet_Service,OnlineSecurity_No_Internet_Service,OnlineSecurity_Yes,OnlineSecurity_Yes,DeviceProtection_No_Internet_Service,DeviceProtection_Yes,TechSupport_No_Internet_Service,TechSupport_Yes,StreamingTV_No_Internet_Service,StreamingTV_Yes,Contract_One_Year,Contract_Two_Year,PaymentMethod_Credit_card,PaymentMethod_Electronic_Check,PaymentMethod_Mailed_Check,tenure,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,29.85,29.85,0
1,5575-GNVDE,1,0,0,0,1,0,0,0,0,0,0,1,1,0,0,1,1,0,1,0,0,0,0,1,0,0,0,1,34,56.95,1889.50,0
2,3668-QPYBK,1,0,0,0,1,0,0,0,0,0,0,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,2,53.85,108.15,1
3,7795-CFOCW,1,0,0,0,0,1,0,0,0,0,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,0,0,0,45,42.30,1840.75,0
4,9237-HQITU,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,2,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,1,0,1,1,1,0,1,0,0,0,0,1,1,0,0,1,1,0,1,0,1,0,1,1,0,0,0,1,24,84.80,1990.50,0
7039,2234-XADUH,0,0,1,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,0,1,0,0,72,103.20,7362.90,0
7040,4801-JZAZL,0,0,1,1,0,1,0,0,0,0,0,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,11,29.60,346.45,0
7041,8361-LTMKD,1,1,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4,74.40,306.60,1
7042,3186-AJIEK,1,0,0,0,1,0,0,1,0,0,0,1,1,0,0,1,1,0,1,0,1,0,1,0,1,0,0,0,66,105.65,6844.50,0

In [78]:
data_done_with_dummy_data.to_csv('preprocessing_data.csv')